name: sign_language_tutor
description: An application for teaching ASL using interactive tutorials.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "^1.0.3"
  firebase_auth: "^1.0.2"
  cloud_firestore: "^1.0.4"
  uuid: 3.0.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  like_button: ^2.0.2
  expandable: ^5.0.1
  font_awesome_flutter: ^9.0.0
  camera: ^0.5.8+17
  tflite: ^1.0.5
  percent_indicator: ^2.1.3
  flutter_tts:

  http: ^0.13.1
  youtube_player_flutter: ^8.0.0
  syncfusion_flutter_gauges: ^18.2.44


dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Round.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/tflite/

  fonts:
  - family: Ubuntu
    fonts:
      - asset: assets/fonts/Ubuntu-Regular.ttf
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        weight: 400

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
